FROM node:18-bullseye
WORKDIR /app
RUN apt-get update && apt-get install -y build-essential libgmp3-dev git
RUN npm i -g snarkjs circom
EXPOSE 8080
COPY prover-server/ /app/prover-server/
WORKDIR /app/prover-server
RUN npm install
CMD ["node","index.js"]